# Generated by Django 3.1.4 on 2021-01-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion_Forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='name',
            field=models.CharField(default='{{ request.user }}', max_length=200),
        ),
    ]
