# Generated by Django 3.1.4 on 2021-01-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion_Forum', '0002_auto_20210104_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='name',
            field=models.CharField(default=None, max_length=500, verbose_name='Имя'),
        ),
    ]
