# Generated by Django 3.1.4 on 2021-01-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion_Forum', '0004_auto_20210107_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='user_photo',
            field=models.ImageField(blank=True, upload_to='comments/'),
        ),
    ]
