# Generated by Django 3.1.4 on 2021-01-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion_Forum', '0009_auto_20210111_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='user_photo',
            field=models.FileField(blank=True, upload_to='comments/'),
        ),
    ]
