# Generated by Django 3.1.4 on 2021-01-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion_Forum', '0010_auto_20210111_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='user_photo',
            field=models.CharField(blank=True, max_length=50000, verbose_name='Photo'),
        ),
    ]
