# Generated by Django 3.1.4 on 2021-01-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion_Forum', '0011_auto_20210111_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='username',
            field=models.CharField(blank=True, max_length=5000, verbose_name='Для валидации'),
        ),
    ]
