# Generated by Django 3.1.4 on 2021-01-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion_Forum', '0012_reviews_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='link',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
