# Generated by Django 3.1.4 on 2021-01-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion_Forum', '0014_auto_20210115_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='link',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
