# Generated by Django 3.1.4 on 2021-01-19 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion_Forum', '0015_auto_20210119_0535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forum',
            old_name='link',
            new_name='slug',
        ),
    ]
