# Generated by Django 3.1.4 on 2021-01-19 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion_Forum', '0018_auto_20210119_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='likes',
        ),
    ]
