# Generated by Django 3.1.4 on 2021-01-21 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion_Forum', '0020_auto_20210120_0416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='podcategory',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RemoveField(
            model_name='podcategory',
            name='father',
        ),
        migrations.AddField(
            model_name='podcategory',
            name='main',
            field=models.ManyToManyField(related_name='tags', to='Discussion_Forum.forum'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Discussion_Forum.category'),
        ),
    ]
