# Generated by Django 3.1.4 on 2021-01-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion_Forum', '0022_auto_20210121_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='opisanie',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
