# Generated by Django 3.1.4 on 2021-01-25 10:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Discussion_Forum', '0023_forum_opisanie'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='likes',
            field=models.ManyToManyField(related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
