# Generated by Django 3.1.4 on 2021-02-03 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion_Forum', '0028_like_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like_2',
            old_name='post',
            new_name='review',
        ),
    ]
