# Generated by Django 3.1.4 on 2021-02-08 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion_Forum', '0029_auto_20210203_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forum',
            options={'ordering': ('date_created',)},
        ),
    ]
