# Generated by Django 3.1.4 on 2021-02-09 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion_Forum', '0031_auto_20210208_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='slug',
        ),
    ]
