# Generated by Django 3.1.4 on 2021-02-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion_Forum', '0032_remove_forum_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='username',
            field=models.CharField(blank=True, max_length=5000, verbose_name='Для валидации'),
        ),
    ]
