# Generated by Django 3.1.4 on 2021-02-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion_Forum', '0033_forum_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
                ('name', models.CharField(blank=True, max_length=2000, verbose_name='name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Связь',
                'verbose_name_plural': 'Свзяь',
            },
        ),
    ]
