# Generated by Django 3.1.4 on 2021-02-16 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion_Forum', '0034_call'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumPopular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vopros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Discussion_Forum.forum')),
            ],
            options={
                'verbose_name': 'Популярная статья',
                'verbose_name_plural': 'Популярные статьи',
            },
        ),
    ]
