# Generated by Django 3.1.4 on 2021-02-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion_Forum', '0036_auto_20210216_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='image',
            field=models.ImageField(blank=True, upload_to='forum-photo', verbose_name='Фотография'),
        ),
    ]
