# Generated by Django 3.1.4 on 2021-02-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion_Forum', '0038_auto_20210216_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='images',
            field=models.ImageField(null=True, upload_to='forum-photo', verbose_name='Фотография'),
        ),
    ]
