# Generated by Django 3.1.4 on 2021-02-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion_Forum', '0044_auto_20210216_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='forum-photo/', verbose_name='Фотография'),
        ),
    ]
