# Generated by Django 3.1.4 on 2021-02-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion_Forum', '0047_remove_forum_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/%d'),
        ),
    ]
