# Generated by Django 3.1.4 on 2021-02-26 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion_Forum', '0048_forum_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='photo',
        ),
    ]
