# Generated by Django 3.1.4 on 2021-02-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_profile_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='admin',
            field=models.BooleanField(default=False, verbose_name='Админ'),
        ),
    ]
