# Generated by Django 3.1.4 on 2021-02-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zayavka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=4000, verbose_name='Название курса')),
                ('fio', models.CharField(blank=True, max_length=4000, verbose_name='ФИО')),
                ('iin', models.CharField(blank=True, max_length=20, verbose_name='ИИН')),
                ('number', models.CharField(blank=True, max_length=40, verbose_name='Номер телефона')),
                ('language', models.CharField(blank=True, max_length=40, verbose_name='Язык обучения')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
