# Generated by Django 3.1.4 on 2021-02-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_zayavka'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='price',
            field=models.CharField(blank=True, max_length=5000, verbose_name='Цена'),
        ),
    ]
