# Generated by Django 3.1.4 on 2021-02-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_courses_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='photo',
            field=models.ImageField(blank=True, upload_to='courses', verbose_name='Фото'),
        ),
    ]
