# Generated by Django 3.1.4 on 2021-02-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_courses_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='description_kk',
            field=models.TextField(max_length=100000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='courses',
            name='description_ru',
            field=models.TextField(max_length=100000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='courses',
            name='name_kk',
            field=models.CharField(max_length=4000, null=True, verbose_name='Название курса'),
        ),
        migrations.AddField(
            model_name='courses',
            name='name_ru',
            field=models.CharField(max_length=4000, null=True, verbose_name='Название курса'),
        ),
    ]
